### PR TITLE
Fixes #2

### LINKED ISSUE #2: Handling multiple commands in a single message
Right now bhattu cannot handle multiple commands in a single message. It only processes the first command.

### PR DESCRIPTION
**Pull request by americast**

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
@americast I think there are merge conflicts. Get the latest tip of master and please rebase this branch. After that this can be merged!

**Comment by americast** [comment]
@pranitbauva1997 Done !

**Comment by americast** [comment]
@pranitbauva1997 Please wait dont merge

**Comment by pranitbauva1997** [comment]
@americast Awesome work dude! Thanks for following this up.

I see you have made this PR from master branch. Please delete the master branch and get the new master branch from `upstream`. How to do that?

`$ git checkout -b random`
`$ git fetch upstream`
`$ git checkout upstream/master`
`$ git checkout -b master`
`$ git push origin master --force`

And the job is done. Now your master branch will exactly match the master branch of this repo!

**Pull request merged**
