### PR TITLE
Issue#15

### PR DESCRIPTION
**Pull request by grapheo12**
Added autogen.py to automate .txt file creation.

### CODE REVIEW

**Comment by berserker1** [comment]
You can write `Closes #15`  in the pr description it will automatically close that issue.

**Comment by berserker1** [comment]
I do not see the .txt file has updated.
Run the script once locally and see if it is doing its job or not.
Then send the updated txt file also.

**Comment by grapheo12** [comment]
Modified the .txt files as asked. Please run json_maker.py and main.py

**Comment by berserker1** [comment]
>You can write Closes #15 in the pr description it will automatically close that issue.

Bhai what about this?

**Comment by grapheo12** [comment]
I thought if someone merges my PR he will do this.

**Pull request closed without merging**
