### PR TITLE
improved clarity

### PR DESCRIPTION
**Pull request by americast**
Messages have text first, tags next.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Hey @americast, Excuse me for closing and re-opening the PR. I just enabled PEP8Speaks on this repo.

**Review by OrkoHunter — COMMENTED** [review]
Hi Sayan, thanks for doing this. I am unable to figure out the new comment view from this PR. Can we test this branch somewhere ?

**Comment by OrkoHunter** [comment]
It'd be great if you could also add a `.pep8speaks.yml` file with 

```
pycodestyle:
    max-line-length: 100
```

**Comment by americast** [comment]
@OrkoHunter I have deployed it. You may test it on slack itself.

**Review by OrkoHunter — APPROVED** [review]
@pep8speaks pep8ify

**Comment by OrkoHunter** [comment]
@americast You must have received a PR from the bot with some style fixes. Please merge it and it will solve _most_ of the issues.

+1 from me.

**Pull request merged**
